source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'mysql2'
gem 'haml-rails'
gem 'cineworld'
gem 'friendly_id', '~> 3.2.1'
gem 'geocoder'
gem 'settingslogic'
gem 'tmdb_party'
gem 'hoptoad_notifier'
