# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nearest_cineworld_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
